default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: randomizer_development







test:
  <<: *default
  database: randomizer_test

production:
  <<: *default
  database: randomizer_production
  username: randomizer
  password: <%= ENV['RANDOMIZER_DATABASE_PASSWORD'] %>
